version: "3"
services:
  ros2:
    build: .
    container_name: TDK_ros
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./src:/TDK_ros/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
